export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  colors: Record<string, string>;
  preview: {
    sidebar: string;
    primary: string;
    background: string;
    card: string;
    text: string;
  };
}

export const themePresets: ThemePreset[] = [
  {
    id: 'default',
    name: 'theme.presets.default.name',
    description: 'theme.presets.default.description',
    colors: {
      '--vbwd-sidebar-bg': '#2c3e50',
      '--vbwd-sidebar-text': 'rgba(255, 255, 255, 0.8)',
      '--vbwd-sidebar-active-bg': 'rgba(255, 255, 255, 0.1)',
      '--vbwd-page-bg': '#f5f5f5',
      '--vbwd-card-bg': '#ffffff',
      '--vbwd-color-primary': '#3498db',
      '--vbwd-color-primary-hover': '#2980b9',
      '--vbwd-text-heading': '#2c3e50',
      '--vbwd-text-body': '#333333',
      '--vbwd-text-muted': '#666666',
      '--vbwd-color-success': '#27ae60',
      '--vbwd-color-danger': '#e74c3c',
      '--vbwd-color-warning': '#f39c12',
      '--vbwd-border-color': '#dddddd',
      '--vbwd-border-light': '#eeeeee',
      '--vbwd-card-shadow': '0 2px 5px rgba(0, 0, 0, 0.05)',
      // Taro plugin color variables
      '--color-primary': '#3498db',
      '--color-primary-dark': '#2980b9',
      '--color-primary-light': '#5dade2',
      '--color-primary-rgb': '52, 152, 219',
      '--color-text-primary': '#333333',
      '--color-text-secondary': '#666666',
      '--color-background': '#f5f5f5',
      '--color-background-secondary': '#ffffff',
      '--color-border': '#dddddd',
      '--color-success': '#27ae60',
      '--color-success-light': '#d5f4e6',
      '--color-success-dark': '#1e8449',
      '--color-warning': '#f39c12',
      '--color-warning-light': '#fdebd0',
      '--color-warning-darker': '#b7590c',
      '--color-error': '#e74c3c',
      '--color-error-light': '#fadbd8',
      '--color-error-dark': '#c0392b',
      '--color-info': '#3498db',
      '--color-info-light': '#d6eaf8',
      '--color-info-dark': '#1f618d',
      '--spacing-xs': '0.25rem',
      '--spacing-sm': '0.5rem',
      '--spacing-md': '1rem',
      '--spacing-lg': '1.5rem',
      '--spacing-xl': '2rem',
      '--border-radius': '0.5rem',
      '--border-radius-sm': '0.25rem',
      '--shadow-sm': '0 2px 5px rgba(0, 0, 0, 0.05)',
    },
    preview: {
      sidebar: '#2c3e50',
      primary: '#3498db',
      background: '#f5f5f5',
      card: '#ffffff',
      text: '#333333',
    }
  },
  {
    id: 'dark',
    name: 'theme.presets.dark.name',
    description: 'theme.presets.dark.description',
    colors: {
      '--vbwd-sidebar-bg': '#1a1a2e',
      '--vbwd-sidebar-text': 'rgba(255, 255, 255, 0.7)',
      '--vbwd-sidebar-active-bg': 'rgba(255, 255, 255, 0.08)',
      '--vbwd-page-bg': '#16213e',
      '--vbwd-card-bg': '#1a1a2e',
      '--vbwd-color-primary': '#60a5fa',
      '--vbwd-color-primary-hover': '#3b82f6',
      '--vbwd-text-heading': '#f3f4f6',
      '--vbwd-text-body': '#d1d5db',
      '--vbwd-text-muted': '#9ca3af',
      '--vbwd-color-success': '#34d399',
      '--vbwd-color-danger': '#f87171',
      '--vbwd-color-warning': '#fbbf24',
      '--vbwd-border-color': '#374151',
      '--vbwd-border-light': '#2d3748',
      '--vbwd-card-shadow': '0 2px 5px rgba(0, 0, 0, 0.3)',
      // Taro plugin color variables
      '--color-primary': '#60a5fa',
      '--color-primary-dark': '#3b82f6',
      '--color-primary-light': '#93c5fd',
      '--color-primary-rgb': '96, 165, 250',
      '--color-text-primary': '#d1d5db',
      '--color-text-secondary': '#9ca3af',
      '--color-background': '#16213e',
      '--color-background-secondary': '#1a1a2e',
      '--color-border': '#374151',
      '--color-success': '#34d399',
      '--color-success-light': '#1f4e3c',
      '--color-success-dark': '#10b981',
      '--color-warning': '#fbbf24',
      '--color-warning-light': '#4a3a1a',
      '--color-warning-darker': '#fcd34d',
      '--color-error': '#f87171',
      '--color-error-light': '#7f2d2d',
      '--color-error-dark': '#fca5a5',
      '--color-info': '#60a5fa',
      '--color-info-light': '#1e3a8a',
      '--color-info-dark': '#bfdbfe',
      '--spacing-xs': '0.25rem',
      '--spacing-sm': '0.5rem',
      '--spacing-md': '1rem',
      '--spacing-lg': '1.5rem',
      '--spacing-xl': '2rem',
      '--border-radius': '0.5rem',
      '--border-radius-sm': '0.25rem',
      '--shadow-sm': '0 2px 5px rgba(0, 0, 0, 0.3)',
    },
    preview: {
      sidebar: '#1a1a2e',
      primary: '#60a5fa',
      background: '#16213e',
      card: '#1a1a2e',
      text: '#d1d5db',
    }
  },
  {
    id: 'forest',
    name: 'theme.presets.forest.name',
    description: 'theme.presets.forest.description',
    colors: {
      '--vbwd-sidebar-bg': '#1b4332',
      '--vbwd-sidebar-text': 'rgba(255, 255, 255, 0.8)',
      '--vbwd-sidebar-active-bg': 'rgba(255, 255, 255, 0.1)',
      '--vbwd-page-bg': '#f0fdf4',
      '--vbwd-card-bg': '#ffffff',
      '--vbwd-color-primary': '#059669',
      '--vbwd-color-primary-hover': '#047857',
      '--vbwd-text-heading': '#1b4332',
      '--vbwd-text-body': '#374151',
      '--vbwd-text-muted': '#6b7280',
      '--vbwd-color-success': '#10b981',
      '--vbwd-color-danger': '#ef4444',
      '--vbwd-color-warning': '#f59e0b',
      '--vbwd-border-color': '#d1d5db',
      '--vbwd-border-light': '#e5e7eb',
      '--vbwd-card-shadow': '0 2px 5px rgba(0, 0, 0, 0.05)',
      // Taro plugin color variables
      '--color-primary': '#059669',
      '--color-primary-dark': '#047857',
      '--color-primary-light': '#1f9b80',
      '--color-primary-rgb': '5, 150, 105',
      '--color-text-primary': '#374151',
      '--color-text-secondary': '#6b7280',
      '--color-background': '#f0fdf4',
      '--color-background-secondary': '#ffffff',
      '--color-border': '#d1d5db',
      '--color-success': '#10b981',
      '--color-success-light': '#d1fae5',
      '--color-success-dark': '#059669',
      '--color-warning': '#f59e0b',
      '--color-warning-light': '#fef3c7',
      '--color-warning-darker': '#d97706',
      '--color-error': '#ef4444',
      '--color-error-light': '#fee2e2',
      '--color-error-dark': '#b91c1c',
      '--color-info': '#059669',
      '--color-info-light': '#d1fae5',
      '--color-info-dark': '#047857',
      '--spacing-xs': '0.25rem',
      '--spacing-sm': '0.5rem',
      '--spacing-md': '1rem',
      '--spacing-lg': '1.5rem',
      '--spacing-xl': '2rem',
      '--border-radius': '0.5rem',
      '--border-radius-sm': '0.25rem',
      '--shadow-sm': '0 2px 5px rgba(0, 0, 0, 0.05)',
    },
    preview: {
      sidebar: '#1b4332',
      primary: '#059669',
      background: '#f0fdf4',
      card: '#ffffff',
      text: '#374151',
    }
  },
  {
    id: 'ocean',
    name: 'theme.presets.ocean.name',
    description: 'theme.presets.ocean.description',
    colors: {
      '--vbwd-sidebar-bg': '#0c4a6e',
      '--vbwd-sidebar-text': 'rgba(255, 255, 255, 0.8)',
      '--vbwd-sidebar-active-bg': 'rgba(255, 255, 255, 0.1)',
      '--vbwd-page-bg': '#f0f9ff',
      '--vbwd-card-bg': '#ffffff',
      '--vbwd-color-primary': '#0284c7',
      '--vbwd-color-primary-hover': '#0369a1',
      '--vbwd-text-heading': '#0c4a6e',
      '--vbwd-text-body': '#334155',
      '--vbwd-text-muted': '#64748b',
      '--vbwd-color-success': '#22c55e',
      '--vbwd-color-danger': '#ef4444',
      '--vbwd-color-warning': '#eab308',
      '--vbwd-border-color': '#cbd5e1',
      '--vbwd-border-light': '#e2e8f0',
      '--vbwd-card-shadow': '0 2px 5px rgba(0, 0, 0, 0.05)',
      // Taro plugin color variables
      '--color-primary': '#0284c7',
      '--color-primary-dark': '#0369a1',
      '--color-primary-light': '#0ea5e9',
      '--color-primary-rgb': '2, 132, 199',
      '--color-text-primary': '#334155',
      '--color-text-secondary': '#64748b',
      '--color-background': '#f0f9ff',
      '--color-background-secondary': '#ffffff',
      '--color-border': '#cbd5e1',
      '--color-success': '#22c55e',
      '--color-success-light': '#dcfce7',
      '--color-success-dark': '#15803d',
      '--color-warning': '#eab308',
      '--color-warning-light': '#fef08a',
      '--color-warning-darker': '#ca8a04',
      '--color-error': '#ef4444',
      '--color-error-light': '#fee2e2',
      '--color-error-dark': '#b91c1c',
      '--color-info': '#0284c7',
      '--color-info-light': '#cffafe',
      '--color-info-dark': '#0c4a6e',
      '--spacing-xs': '0.25rem',
      '--spacing-sm': '0.5rem',
      '--spacing-md': '1rem',
      '--spacing-lg': '1.5rem',
      '--spacing-xl': '2rem',
      '--border-radius': '0.5rem',
      '--border-radius-sm': '0.25rem',
      '--shadow-sm': '0 2px 5px rgba(0, 0, 0, 0.05)',
    },
    preview: {
      sidebar: '#0c4a6e',
      primary: '#0284c7',
      background: '#f0f9ff',
      card: '#ffffff',
      text: '#334155',
    }
  },
  {
    id: 'sunset',
    name: 'theme.presets.sunset.name',
    description: 'theme.presets.sunset.description',
    colors: {
      '--vbwd-sidebar-bg': '#7c2d12',
      '--vbwd-sidebar-text': 'rgba(255, 255, 255, 0.8)',
      '--vbwd-sidebar-active-bg': 'rgba(255, 255, 255, 0.1)',
      '--vbwd-page-bg': '#fff7ed',
      '--vbwd-card-bg': '#ffffff',
      '--vbwd-color-primary': '#ea580c',
      '--vbwd-color-primary-hover': '#c2410c',
      '--vbwd-text-heading': '#7c2d12',
      '--vbwd-text-body': '#44403c',
      '--vbwd-text-muted': '#78716c',
      '--vbwd-color-success': '#16a34a',
      '--vbwd-color-danger': '#dc2626',
      '--vbwd-color-warning': '#d97706',
      '--vbwd-border-color': '#d6d3d1',
      '--vbwd-border-light': '#e7e5e4',
      '--vbwd-card-shadow': '0 2px 5px rgba(0, 0, 0, 0.05)',
      // Taro plugin color variables
      '--color-primary': '#ea580c',
      '--color-primary-dark': '#c2410c',
      '--color-primary-light': '#f97316',
      '--color-primary-rgb': '234, 88, 12',
      '--color-text-primary': '#44403c',
      '--color-text-secondary': '#78716c',
      '--color-background': '#fff7ed',
      '--color-background-secondary': '#ffffff',
      '--color-border': '#d6d3d1',
      '--color-success': '#16a34a',
      '--color-success-light': '#dcfce7',
      '--color-success-dark': '#15803d',
      '--color-warning': '#d97706',
      '--color-warning-light': '#fef3c7',
      '--color-warning-darker': '#b45309',
      '--color-error': '#dc2626',
      '--color-error-light': '#fee2e2',
      '--color-error-dark': '#991b1b',
      '--color-info': '#ea580c',
      '--color-info-light': '#ffedd5',
      '--color-info-dark': '#7c2d12',
      '--spacing-xs': '0.25rem',
      '--spacing-sm': '0.5rem',
      '--spacing-md': '1rem',
      '--spacing-lg': '1.5rem',
      '--spacing-xl': '2rem',
      '--border-radius': '0.5rem',
      '--border-radius-sm': '0.25rem',
      '--shadow-sm': '0 2px 5px rgba(0, 0, 0, 0.05)',
    },
    preview: {
      sidebar: '#7c2d12',
      primary: '#ea580c',
      background: '#fff7ed',
      card: '#ffffff',
      text: '#44403c',
    }
  }
];
